teleop:
    ros__parameters:
        require_enable_button: True
        enable_button: 5        # Left trigger button
        enable_turbo_button: 4  # Right trigger button
        axis_linear: # Left thumb stick vertical
            x: 1
            y: 0
            z: -1
        scale_linear:
            x: 0.5
            y: 0.5
            z: 0.0
        scale_linear_turbo:
            x: 1.0
            y: 1.0
            z: 0.0
        axis_angular: # Left thumb stick horizontal
            roll: -1
            pitch: -1
            yaw: 2
        scale_angular:
            roll: 0.0
            pitch: 0.0
            yaw: 0.5
        inverted_reverse: False
        publish_stamped_twist: False
        frame: teleop_twist_joy
        ros_remappings:
            topics:
                # subscribers
                - "joy:joy"
                # publishers
                - "cmd_vel:forklift/teleop_twist_cmd"
            #services:
            # services servers: none
            # services clients: none
            #actions:
            # action servers: none
            # action clients: none
        ros_execution:
            node_package: "teleop_twist_joy"
            node_executable: "teleop_node"
            output: screen
            emulate_tty: False
            respawn: False
            respawn_delay: 0
